'use client'
import { useCallback, useEffect, useState } from 'react'
import { POLICY_MESSAGE, RETURN_MESSAGE, REASONS } from '@/lib/after-sales-policy'
const label = (v: string) => v.replace(/_/g, ' ')
const money = (v: number) => `₦${((v || 0) / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })}`
const closed = ['refunded', 'resolved', 'rejected']
function actionsFor(c: any, mode: string): string[] {
  if (!c) return [];
  const active = !['refunded', 'resolved', 'rejected'].includes(c.status);
  const actions = ['message'];
  if (mode === 'customer') {
    if (!c.appealedAt) actions.push('appeal');
    if (c.status === 'awaiting_resolution') actions.push('accept_refund');
    if (c.status === 'awaiting_arrangements') actions.push('accept_arrangements');
    if (c.status === 'awaiting_return') actions.push('return_shipped');
  }
  if (active && mode === 'vendor') {
    if (['requested', 'admin_review'].includes(c.status)) actions.push('respond');
    if (c.kind === 'replacement' && !c.replacementTracking) actions.push('offer_refund');
    if (c.status === 'inspection') actions.push('inspect');
  }
  if (active && mode === 'admin') {
    if (c.kind === 'replacement' && !c.replacementTracking) actions.push('offer_refund');
    if (['requested', 'admin_review', 'awaiting_arrangements', 'awaiting_logistics'].includes(c.status)) actions.push('approve_return');
    if (c.status === 'awaiting_logistics') actions.push('confirm_logistics');
    if (c.status === 'return_in_transit') actions.push('verify_return');
    if (c.status === 'inspection') actions.push('inspect');
    if (c.inspection === 'contested') actions.push('accept_inspection');
    if (!c.returnWaivedAt && !c.replacementTracking) actions.push('waive_return');
    if (!c.refundedAt && (c.inspection === 'accepted' || c.returnWaivedAt)) actions.push('refund');
    if (c.kind === 'replacement' && c.stockReservedAt && !c.replacementTracking && (c.inspection === 'accepted' || c.returnWaivedAt)) actions.push('replacement_shipped');
    if (c.status === 'replacement_in_transit') actions.push('verify_replacement');
    actions.push('extend_deadline', 'reject');
    if (c.kind !== 'replacement') actions.push('resolve');
  }
  return actions;
}

export default function AfterSalesCenter({ mode = 'customer' }: { mode?: 'customer' | 'vendor' | 'admin' }) {
 const [balance,setBalance]=useState<any>(null)
 const [orders,setOrders]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('all'),[store,setStore]=useState('')
 const [selection,setSelection]=useState<any>(null),[form,setForm]=useState<any>({}),[evidence,setEvidence]=useState<string[]>([]),[offset,setOffset]=useState<number|null>(null),[notice,setNotice]=useState('')
 const load=useCallback(async(start=0)=>{setBusy(true);setError('');try{const orderId=new URLSearchParams(window.location.search).get('orderId');const r=await fetch(`/api/after-sales?${new URLSearchParams({mode,offset:String(start),...(orderId?{orderId}:{})})}`,{credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.error);setOrders(p=>start?[...p,...d.orders]:d.orders);setOffset(d.nextOffset);if(mode==='vendor'&&start===0){const br=await fetch('/api/after-sales/balance',{credentials:'include'});const bd=await br.json();if(!br.ok)throw new Error(bd.error);setBalance(bd)}}catch(e:any){setError(e.message)}finally{setBusy(false)}},[mode])
 useEffect(()=>{void load()},[load])
 function select(order:any,line:any,c?:any){setSelection({order,line,c});setEvidence([]);setError('');setForm({kind:'return',quantity:1,reason:'wrong_item',refundMethod:'wallet',action:'message',fault:'vendor',inspection:'accepted'})}
 const field=(key:string,title:string,type='text')=><label className="grid gap-1" key={key}>{title}<input aria-label={title} name={key} type={type} className="border rounded p-3 bg-background" value={form[key]||''} onChange={e=>setForm((f:any)=>({...f,[key]:e.target.value}))}/></label>
 const choice=(key:string,title:string,values:readonly string[])=><label className="grid gap-1">{title}<select aria-label={title} name={key} className="border rounded p-3 bg-background" value={form[key]} onChange={e=>setForm((f:any)=>({...f,[key]:e.target.value}))}>{values.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/after-sales',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,action:selection.c?form.action:mode==='admin'?'verify_delivery':'create',orderId:selection.order.orderId,lineId:selection.line.id,caseId:selection.c?.id,quantity:Number(form.quantity),evidence})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelection(null);setNotice('Saved. Your case timeline shows the next step.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{const d=new FormData();d.append('file',file);d.append('upload_preset','my_unsigned_preset');const r=await fetch('https://api.cloudinary.com/v1_1/ddhtduti2/image/upload',{method:'POST',body:d});const data=await r.json();if(!r.ok||!data.secure_url)throw new Error('Could not upload photo');setEvidence(p=>[...p,data.secure_url].slice(0,5))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const c=selection?.c
 const actions=actionsFor(c,mode)
 const stores=[...new Set(orders.flatMap(o=>o.lines.map((l:any)=>l.storeId)))] as string[]
 return <main className="max-w-5xl mx-auto p-5 space-y-5"><h1 className="text-3xl font-bold">{mode==='customer'?'Returns & Replacements':'Returns & Disputes'}</h1><a className="underline" href={mode === "customer" ? "/service-claims" : `/${mode}/service-claims`}>Service issues</a><p>{POLICY_MESSAGE}</p><p>{RETURN_MESSAGE}</p><p>Inspection compares the item with its condition when received. Existing damage does not invalidate a damage claim. Approved refunds cover the paid item amount and applicable tax. Original delivery is excluded for change-of-mind returns.</p>
 <div className="flex flex-wrap gap-2">{['all','return','replacement','refunds','action_needed'].map(t=><button key={t} className={`border rounded p-3 ${t===tab?'bg-primary text-primary-foreground':''}`} onClick={()=>setTab(t)}>{label(t)}</button>)}<button disabled={busy} onClick={()=>void load()}>Refresh</button></div>
 {mode!=='customer'&&<label>Store <select value={store} onChange={e=>setStore(e.target.value)}><option value="">All stores</option>{stores.map(id=><option key={id}>{id}</option>)}</select></label>}
 {mode==='vendor'&&balance&&<aside className="border rounded p-4"><h2>Protected earnings across your stores</h2><p>In escrow: {money(balance.inEscrow*100)} · Pending: {money(balance.pending*100)} · On hold: {money(balance.onHold*100)} · Available wallet: {money(balance.available*100)}</p></aside>}
 {busy&&<p role="status">Working…</p>}{error&&<p role="alert" className="bg-red-50 text-red-800 p-3">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {selection&&<form onSubmit={save} className="border rounded-xl p-5"><fieldset disabled={busy} className="space-y-4"><h2 className="font-semibold text-xl">{selection.line.title}</h2><p>Ordered: {(selection.line.selectedVariants||[]).map((v:any)=>`${v.label}: ${v.value}`).join(', ')||'Standard item'}</p>
 {mode==='admin'&&!c?<>{field('note','Delivery verification explanation')}<p>Attach courier delivery proof. Verification starts a full 48-hour hold.</p></>:c?<><p>Logistics payer: {c.logisticsPayer||'To be agreed'} · Quote: {money(c.logisticsCents)}</p>{c.returnAddress&&<p>Return to: {c.returnAddress}</p>}{choice('action','Action',actions)}{field('note','Message or decision explanation')}{mode==='vendor'&&form.action==='respond'&&choice('vendorAgreement','Return agreement',['accept_return','contest'])}
 {form.action==='approve_return'&&<>{choice('fault','Responsible party',['customer','vendor','courier'])}{field('returnAddress','Agreed return address')}{field('logisticsAmount','Logistics quote (NGN)','number')}{c.kind==='replacement'&&<>{field('confirmedVariant','Confirm the requested replacement exactly')}{field('replacementVariantLabel','Variant label (for example Size)')}{field('replacementVariantValue','Replacement value (for example 41)')}</>}</>}
 {['return_shipped','replacement_shipped'].includes(form.action)&&<>{field('courier','Courier')}{field('trackingNumber','Tracking number')}</>}{form.action==='confirm_logistics'&&<>{field('courier','Booked courier')}{field('logisticsReference','Paid courier booking reference')}<p>Attach the courier receipt showing the agreed payer. The five-day return deadline starts after verification.</p></>}{form.action==='inspect'&&choice('inspection','Inspection outcome',['accepted','contested'])}{form.action==='extend_deadline'&&field('hours','Extension in hours (1–720)','number')}{form.action==='refund'&&<>{field('shippingRefundAmount','Original delivery refund (NGN, fault claims only)','number')}{field('returnCostRefundAmount','Return logistics reimbursement (NGN, receipts required)','number')}</>}{form.action==='refund'&&c.refundMethod==='original'&&field('providerRefundReference','Confirmed original-payment refund reference')}
 </>:<>{choice('kind','Requested resolution',['return','replacement','complaint'])}{choice('reason','Reason',REASONS.filter(r=>r!=='service_issue'))}{field('quantity',`Quantity (up to ${selection.line.quantity-(selection.line.refundedQuantity||0)})`,'number')}{field('description','Describe the issue')}{field('receivedVariant','What size, colour or item arrived?')}{form.kind==='replacement'&&field('desiredVariant','Requested replacement variant')}{form.reason!=='not_received'&&field('pickupAddress','Return pickup address')}{choice('refundMethod','Preferred refund destination',['wallet','original'])}<p>Choosing wallet authorizes wallet credit for an approved refund. Original-payment refunds require payment-provider processing.</p></>}
 <label className="grid gap-1">Evidence photos (up to five; video is optional)<input type="file" accept="image/*" disabled={evidence.length>=5} onChange={e=>void upload(e.target.files?.[0])}/></label><div className="flex gap-2">{evidence.map((url,i)=><button type="button" key={i} aria-label="Remove photo" onClick={()=>setEvidence(p=>p.filter((_,n)=>n!==i))}><img alt="Evidence preview" src={url} className="w-20 h-20 object-contain"/></button>)}</div><button type="submit" className="bg-primary text-primary-foreground rounded p-3">Submit</button><button type="button" className="border rounded p-3 ml-3" onClick={()=>setSelection(null)}>Close form</button></fieldset></form>}
 {orders.map(order=><section key={order.orderId} className="border rounded-xl p-5 space-y-4"><h2 className="font-semibold">Order #{order.orderId.slice(-8).toUpperCase()}</h2>{order.legacyDispute&&mode==="admin"&&<button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch("/api/after-sales",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"migrate_dispute",orderId:order.orderId})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Review earlier dispute</button>}
 {tab==='all'&&order.lines.filter((l:any)=>!store||l.storeId===store).map((line:any)=><div key={line.id} className="border-t pt-3 space-y-2"><h3>{line.title} × {line.quantity} · {money(line.amountCents-(line.refundedCents||0))}</h3><p>{line.cancelled?'Cancelled':line.refundedQuantity>=line.quantity?'Refunded':!['escrow','released','completed'].includes(order.paymentStatus)?'Payment pending or being reconciled':order.cases.some((v:any)=>v.lineId===line.id&&!closed.includes(v.status))?(line.settledAt?'Late claim — funding review':'On hold — case open'):line.settledAt?'Cleared':line.availableAt?`Pending clearance until ${new Date(line.availableAt).toLocaleString()}`:'In escrow — awaiting verified delivery'}</p>{mode==='admin'&&!line.availableAt&&!line.cancelled&&!line.settledAt&&<button onClick={()=>select(order,line)}>Verify delivery proof</button>}{mode==='customer'&&!line.cancelled&&line.refundedQuantity<line.quantity&&['escrow','released','completed'].includes(order.paymentStatus)&&!order.cases.some((v:any)=>v.lineId===line.id&&!closed.includes(v.status))&&<button className="border rounded p-3" onClick={()=>select(order,line)}>Return, replace or report a problem</button>}</div>)}
 {order.cases.filter((v:any)=>(!store||v.storeId===store)&&(tab==='all'||(tab==='refunds'?v.status==='refunded':tab==='action_needed'?!closed.includes(v.status):v.kind===tab))).map((v:any)=><article key={v.id} className="border-t pt-4 space-y-2"><h3 className="font-semibold">{v.title} · {label(v.status)}</h3><p>{v.description}</p><p>Next: {v.nextActor || "Review"}</p><p>Item estimate: {money(v.amountCents)} · Logistics: {v.logisticsPayer||'Under review'}</p>{v.deadline&&!closed.includes(v.status)&&<p>Next action due: {new Date(v.deadline).toLocaleString()}</p>}{v.logisticsReference&&<p>Return booking: {v.arrangementCourier} · {v.logisticsReference}</p>}{v.returnTracking&&<p>Return: {v.returnTracking.courier} · {v.returnTracking.number}</p>}{v.replacementTracking&&<p>Replacement: {v.replacementTracking.courier} · {v.replacementTracking.number}</p>}<ol>{v.history.map((h:any,i:number)=><li key={i}>{new Date(h.at).toLocaleString()} · {h.actorLabel || "Update"} — {h.message}</li>)}</ol><div className="flex flex-wrap gap-2">{v.evidence.map((url:string,i:number)=><a key={i} href={url} target="_blank" rel="noreferrer"><img alt={`Case evidence ${i+1}`} src={url} className="w-32 h-32 object-contain"/></a>)}</div><button className="border rounded p-3" onClick={()=>select(order,order.lines.find((l:any)=>l.id===v.lineId),v)}>Open request</button></article>)}
 </section>)}{!busy&&!orders.length&&<p>No orders or requests yet. Sign in to view your purchases.</p>}{offset!==null&&<button disabled={busy} onClick={()=>void load(offset)}>Load more</button>}
 </main>
}
