'use client'
import { useCallback, useEffect, useState } from 'react'
export default function ServiceClaimsPanel({ mode = 'customer' }: { mode?: 'customer' | 'vendor' | 'admin' }) {
 const [claims,setClaims]=useState<any[]>([]),[bookingId,setBookingId]=useState(''),[description,setDescription]=useState(''),[resolution,setResolution]=useState('reperformance'),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{setBusy(true);try{const r=await fetch(`/api/service-claims?mode=${mode}`,{credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.error);setClaims(d.claims);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}},[mode])
 useEffect(()=>{setBookingId(new URLSearchParams(window.location.search).get('bookingId')||'');void load()},[load])
 async function save(input:any){setBusy(true);setError('');try{const r=await fetch('/api/service-claims',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const d=await r.json();if(!r.ok)throw new Error(d.error);setDescription('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="max-w-4xl mx-auto p-5 space-y-5"><h1 className="text-3xl font-bold">Service issues</h1><p>Request re-performance, a refund review or another remedy. Recorded online deposits and documented offline payments are reviewed separately. Goods return and parcel inspection rules do not apply.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{busy&&<p role="status">Working…</p>}
 {mode==='customer'&&<form onSubmit={e=>{e.preventDefault();void save({action:'create',bookingId,description,requestedResolution:resolution,evidence:[]})}} className="border rounded p-5 space-y-3"><label className="grid gap-1">Booking ID<input required className="border rounded p-3" value={bookingId} onChange={e=>setBookingId(e.target.value)}/></label><label className="grid gap-1">Requested remedy<select className="border rounded p-3" value={resolution} onChange={e=>setResolution(e.target.value)}>{['reperformance','refund','other'].map(v=><option key={v}>{v}</option>)}</select></label><label className="grid gap-1">Describe the service issue<textarea required className="border rounded p-3" value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy} className="border rounded p-3">Submit service issue</button></form>}
 {claims.map(c=><section className="border rounded p-5 space-y-3" key={c._id}><h2 className="text-xl font-semibold">{c.title} · {c.status.replace(/_/g,' ')}</h2><p>{c.description}</p><p>Requested: {c.requestedResolution}. Recorded online payment: ₦{Number(c.paidOnline||0).toLocaleString()}.</p><ol>{c.history.map((h:any,i:number)=><li key={i}>{new Date(h.at).toLocaleString()} — {h.message}</li>)}</ol><label className="grid gap-1">Message or decision explanation<textarea className="border rounded p-3" value={notes[c._id]||''} onChange={e=>setNotes(n=>({...n,[c._id]:e.target.value}))}/></label><div className="flex gap-2 flex-wrap">{['message',...(mode==='admin'?['reperformance_agreed','resolved','rejected']:[])].map(action=><button disabled={busy} key={action} className="border rounded p-3" onClick={()=>void save({bookingId:c.bookingId,action,note:notes[c._id]})}>{action.replace(/_/g,' ')}</button>)}</div></section>)}<button disabled={busy} onClick={()=>void load()}>Refresh</button></main>
}
