export const NIGERIA_STATE_CITY_OPTIONS: Record<string, string[]> = {
  Lagos: [
    "Ikeja",
    "Maryland",
    "Anthony",
    "Ilupeju",
    "Palmgroove",
    "Jibowu",
    "Yaba",
    "Surulere",
    "Mushin",
    "Oshodi",
    "Isolo",
    "Okota",
    "Festac",
    "Satellite Town",
    "Apapa",
    "Ojo",
    "Iba",
    "Magodo",
    "Omole",
    "Ojodu Berger",
    "Ogba",
    "Agege",
    "Ogudu",
    "Ketu",
    "Gbagada",
    "Iju-Ishaga",
    "Abule-Egba",
    "Iyana-Ipaja",
    "Ayobo",
    "Egbeda",
    "Ejigbo",
    "Ikotun",
    "Igando",
    "Marina",
    "Lagos-Island",
    "Ikoyi",
    "Victoria Island",
    "Lekki-Phase 1",
    "Elegushi",
    "Jakande",
    "Agungi",
    "Chevron",
    "Ikota",
    "VGC",
    "Ajah",
    "Abraham Adesanya",
    "Ikorodu",
  ],
  Abuja: ["Maitama", "Wuse", "Garki", "Asokoro", "Gwarinpa"],
  Abia: ["Umuahia", "Aba"],
  "Akwa-Ibom": ["Uyo", "Eket"],
  Adamawa: ["Yola", "Mubi"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
  Bauchi: ["Bauchi", "Azare"],
  Benue: ["Makurdi", "Gboko"],
  Borno: ["Maiduguri", "Biu"],
  "Cross-River": ["Calabar", "Ikom"],
  Delta: ["Asaba", "Warri", "Sapele"],
  Ebonyi: ["Abakaliki", "Afikpo"],
  Edo: ["Benin City", "Auchi"],
  Ekiti: ["Ado-Ekiti", "Ikere"],
  Enugu: ["Enugu", "Nsukka"],
  Gombe: ["Gombe", "Kaltungo"],
  Imo: ["Owerri", "Orlu"],
  Jigawa: ["Dutse", "Hadejia"],
  Kaduna: ["Kaduna", "Zaria"],
  Kano: ["Kano", "Wudil"],
  Katsina: ["Katsina", "Daura"],
  Kebbi: ["Birnin Kebbi", "Argungu"],
  Kogi: ["Lokoja", "Okene"],
  Kwara: ["Ilorin", "Offa"],
  Nasarawa: ["Lafia", "Keffi"],
  Niger: ["Minna", "Suleja"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sango Ota"],
  Ondo: ["Akure", "Ondo Town"],
  Osun: ["Osogbo", "Ife", "Ilesa"],
  Oyo: ["Ibadan", "Ogbomoso"],
  Plateau: ["Jos", "Bukuru"],
  Rivers: ["Port Harcourt", "Obio-Akpor"],
  Sokoto: ["Sokoto", "Tambuwal"],
  Taraba: ["Jalingo", "Wukari"],
  Yobe: ["Damaturu", "Potiskum"],
  Zamfara: ["Gusau", "Kaura Namoda"],
}

export const NIGERIA_STATES = Object.keys(NIGERIA_STATE_CITY_OPTIONS)
